happy-soup/unpackaged/unpackaged/objects/Animal__c.object
<CustomObject>
    <fields>
        <fullName>Species__c</fullName>
        <label>Species</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bear</fullName>
                </value>
                <value>
                    <fullName>Elephant</fullName>
                </value>
                <value>
                    <fullName>Giraffe</fullName>
                </value>
                <value>
                    <fullName>Gorilla</fullName>
                </value>
                <value>
                    <fullName>Lion</fullName>
                </value>
                <value>
                    <fullName>Parrot</fullName>
                </value>
                <value>
                    <fullName>Penguin</fullName>
                </value>
                <value>
                    <fullName>Tiger</fullName>
                </value>
                <value>
                    <fullName>Tortoise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zoo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zoo</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Zoo__c.Name</field>
                <operation>contains</operation>
                <value>Cleveland</value>
            </filterItems>
            <filterItems>
                <field>$Source.Quantity__c</field>
                <operation>lessOrEqual</operation>
                <valueField>Zoo__c.Capacity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Zoo__c</referenceTo>
        <relationshipLabel>Animals</relationshipLabel>
        <relationshipName>Animals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

happy-soup/unpackaged/unpackaged/objects/Zoo__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Zoo</label>
    <nameField>
        <label>Zoo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

happy-soup/main/default/classes/AnimalDA.cls
public with sharing class AnimalDA implements AnimalDAInterface{
	
	public Animal__c queryAnimalByRecordId(Id recordId){
		try {
			Animal__c a = [
					SELECT Id,
							Name,
							Species__c,
							Zoo__c,
							Zoo__r.Admission__c,
							Zoo__r.Website__c,
							Zoo__r.Name,
							Zoo__r.Address__c
					FROM Animal__c
					WHERE Id = :recordId
					LIMIT 1
			];

			return a;
		}catch(Exception ex){
			System.debug(ex.getMessage());
			throw ex;
		}
	}
}