happy-soup/unpackaged/unpackaged/objects/PageText__c.object
<CustomObject>
    <fields>
        <fullName>PageName__c</fullName>
        <label>Page Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PageSection__c</fullName>
        <label>Page Section</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>The text that goes in the specified section</description>
        <inlineHelpText>The text that goes in the specified section</inlineHelpText>
        <label>Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Page Text</label>
    <nameField>
        <label>Page Text Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

personalDev/happy-soup/unpackaged/unpackaged/classes/TextPageController.cls
public class TextPageController {
	
	public List<PageText__c> textBlurbs {get; private set;}
	public Map<String, String> boxText {get; private set;}

	public TextPageController() {
		textBlurbs = queryPageTextsForTextPage();
		boxText = initializeBoxTexts();
	}

	public List<PageText__c> queryPageTextsForTextPage(){
		return [
			SELECT Id, Name, PageSection__c, Text__c
			FROM PageText__c
			WHERE PageName__c = 'TextPage'
		];
	}

	public Map<String, String> initializeBoxTexts(){
		Map<String, String> tempBoxText = new Map<String, String>();
		for(PageText__c pt : textBlurbs){
			if((pt.PageSection__c).contains('Box')){
				tempBoxText.put(pt.PageSection__c, pt.Text__c);
			}
		}
		return tempBoxText;
	}
}