sfdx-movierentals/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

movie-rentals-lwc/objects/Title__c/fields/AvailableStock__c.field-meta.xml
<CustomField>
    <fullName>AvailableStock__c</fullName>
    <label>Available Stock</label>
    <summaryFilterItems>
        <field>Stock__c.Status__c</field>
        <operation>equals</operation>
        <value>Available</value>
    </summaryFilterItems>
    <summaryForeignKey>Stock__c.Title__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

personalDev/sfdx-movierentals/main/default/objects/Title__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>The Genre of the Movie Title</description>
    <inlineHelpText>The Genre of the Movie Title</inlineHelpText>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Sci-Fi</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
            <value>
                <fullName>Documentary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-movierentals/main/default/objects/Title__c/fields/TotalStock__c.field-meta.xml
<CustomField>
    <fullName>TotalStock__c</fullName>
    <label>Total Stock</label>
    <summaryForeignKey>Stock__c.Title__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/TitleAuraService.cls
public with sharing class TitleAuraService {
    
    @AuraEnabled
    public static List<Title__c> getLatestTitles(Integer limiter){
        List<Title__c> titles = [
            SELECT Id, Name, Genre__c, Thumbnail__c, AvailableStock__c, TotalStock__c 
            FROM Title__c 
            LIMIT :limiter
        ];
        return titles;
    }

    @AuraEnabled
    public static List<Title__c> getOutOfStockTitles(){
        List<Title__c> outOfStockTitles = [
            SELECT Id, Name, Genre__c, Thumbnail__c, AvailableStock__c, TotalStock__c
            FROM Title__c
            WHERE AvailableStock__c = 0
        ];
        return outOfStockTitles;
    }
}