sfdx-movierentals/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

personalDev/sfdx-movierentals/main/default/objects/Title__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>The Genre of the Movie Title</description>
    <inlineHelpText>The Genre of the Movie Title</inlineHelpText>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Sci-Fi</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
            <value>
                <fullName>Documentary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

personalDev/sfdx-movierentals/main/default/objects/Title__c/fields/Is_Featured__c.field-meta.xml
<CustomField>
    <fullName>Is_Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Featured</label>
    <type>Checkbox</type>
</CustomField>

personalDev/happy-soup/main/default/classes/AmrHomeController.cls
public with sharing class AmrHomeController {
	
	public List<Title__c> FeaturedTitles {get; private set;}

	public AmrHomeController() {
		
	}



	@RemoteAction
	public static String myRemoteAction() {
		return 'Some Response';
	}

	@RemoteAction
	public static List<Title__c> queryFeaturedTitles(){
		return [
			SELECT Id, Name, Description__c, Genre__c
			FROM Title__c
			WHERE Is_Featured__c = true
			ORDER BY LastModifiedDate DESC
			LIMIT 20
		];


	}


	@RemoteAction
	public static List<Schema.PicklistEntry> queryAllGenres() {

		Schema.DescribeFieldResult fieldResult = Title__c.Genre__c.getDescribe();
		return fieldResult.getPicklistValues();
	}
}