sfdx-movierentals/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

personalDev/sfdx-movierentals/main/default/objects/Title__c/fields/Is_Featured__c.field-meta.xml
<CustomField>
    <fullName>Is_Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Featured</label>
    <type>Checkbox</type>
</CustomField>

personalDev/happy-soup/main/default/classes/FeaturedTitleManagerController.cls
public class FeaturedTitleManagerController {
	private ApexPages.StandardSetController setController {get; set;}

	public FeaturedTitleManagerController(ApexPages.StandardSetController setController) {
		this.setController = setController;
		this.setController.addFields(new List<String>{
			'Is_Featured__c'
			});
	}

	public PageReference toggleFeaturedTitles(){
		List<Title__c> titles = (List<Title__c>) setController.getSelected();
		for(Title__c title : titles){
			title.Is_Featured__c = !title.Is_Featured__c;
		}

		return setController.save();
	}
}