sfdx-movierentals/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

movie-rentals-lwc/objects/Title__c/fields/AvailableStock__c.field-meta.xml
<CustomField>
    <fullName>AvailableStock__c</fullName>
    <label>Available Stock</label>
    <summaryFilterItems>
        <field>Stock__c.Status__c</field>
        <operation>equals</operation>
        <value>Available</value>
    </summaryFilterItems>
    <summaryForeignKey>Stock__c.Title__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

personalDev/sfdx-movierentals/main/default/objects/Title__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>The Genre of the Movie Title</description>
    <inlineHelpText>The Genre of the Movie Title</inlineHelpText>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Sci-Fi</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
            <value>
                <fullName>Documentary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

personalDev/sfdx-movierentals/main/default/objects/Title__c/fields/Is_Featured__c.field-meta.xml
<CustomField>
    <fullName>Is_Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Featured</label>
    <type>Checkbox</type>
</CustomField>

sfdx-movierentals/main/default/objects/Title__c/fields/TotalStock__c.field-meta.xml
<CustomField>
    <fullName>TotalStock__c</fullName>
    <label>Total Stock</label>
    <summaryForeignKey>Stock__c.Title__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

personalDev/movierentals/main/default/classes/TitleDA.cls
public with sharing class TitleDA implements TitleDAI{

    public List<Title__c> queryLimitedTitles(Integer limitter) {
        return [
        SELECT Id,
            AvailableStock__c,
            TotalStock__c,
            Thumbnail__c,
            Genre__c,
            Name,
            Is_Featured__c
        FROM Title__c
        ORDER BY IS_Featured__c DESC
        LIMIT :limitter];
    }
}