personalDev/happy-soup/unpackaged/unpackaged/objects/Rental__c.object
<CustomObject>
    <fields>
        <fullName>Stock__c</fullName>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>Rentals</relationshipLabel>
        <relationshipName>Rentals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rental</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rental Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-movierentals/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-movierentals/main/default/objects/Stock__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

happy-soup/main/default/classes/StockTriggerFacade.cls
public with sharing class StockTriggerFacade {


	private RentalGenerator rentalGen = new RentalHistoryGenerator();
	private RentalDAO rentalAccessor = new RentalDataAccessor();

	public void saveRentalHistory(Map<Id, Stock__c> oldStockMap, List<Stock__c> updatedStock) {

		List<Stock__c> newlyRentedStock = getNewlyRentedStock(oldStockMap, updatedStock);
		List<Rental__c> rentals = rentalGen.createRentals(newlyRentedStock);
		rentalAccessor.saveRentals(rentals);
	}



	private List<Stock__c> getNewlyRentedStock(Map<Id, Stock__c> oldStockMap, List<Stock__c> updatedStock){
		List<Stock__c> newlyRentedStock = new List<Stock__c>();

		for(Stock__c stock : updatedStock){
			String oldStatus = oldStockMap.get(stock.Id).Status__c;
			String newStatus = stock.Status__c;

			if(hasBeenRented(oldStatus, newStatus)){
				newlyRentedStock.add(stock);
			}
		}

		return newlyRentedStock;
	}



	private Boolean hasBeenRented(String oldStatus, String newStatus){
		return oldStatus != StockDataAccessor.STOCK_STATUS_RENTED && newStatus == StockDataAccessor.STOCK_STATUS_RENTED;
	}
}