sfdx-movierentals/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-movierentals/main/default/objects/Stock__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

personalDev/sfdx-movierentals/main/default/objects/Stock__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <referenceTo>Title__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-movierentals/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

happy-soup/unpackaged/unpackaged/classes/TitleStocker.cls
public with sharing class TitleStocker {
    
    public List<Stock__c> existingStock {get; private set;}
    public Integer rowNumber {get; set;}

    private List<Stock__c> stockToDelete = new List<Stock__c>();
    private Id titleId;

    private StockDataAccessor stockAccessor = new StockDataAccessor();

    public TitleStocker(Id titleId) {
        this.titleId = titleId;
        this.existingStock = stockAccessor.queryStock(titleId);
    }

    public void addStock(){
        Stock__c stock = createStock();
        existingStock.add(stock);
    }

    public void removeStock(){
        if(existingStock[rowNumber].Id != null){
            stockToDelete.add(existingStock[rowNumber]);
        }

        existingStock.remove(rowNumber);

    }

    public void saveChanges(){
        stockAccessor.saveStock(existingStock);
        stockAccessor.deleteStock(stockToDelete);

    }

    private Stock__c createStock(){
        return new Stock__c(Title__c = titleId, Status__c = 'Available');
    }


}