sfdx-movierentals/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-movierentals/main/default/objects/Stock__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

personalDev/sfdx-movierentals/main/default/objects/Stock__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <referenceTo>Title__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-movierentals/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

personalDev/happy-soup/main/default/classes/StockDataAccessor.cls
public with sharing class StockDataAccessor {
	
	public static String STOCK_STATUS_RENTED = 'Rented';
	public static String STOCK_STATUS_AVAILABLE = 'Available';
	public static String STOCK_STATUS_MISSING = 'Missing';

	public List<Stock__c> queryStock(Id titleId){
		return [
			SELECT Id, Name, Status__c, DueDate__c
			FROM Stock__c
			WHERE Title__c = :titleId
		];

	}


	public void saveStock(List<Stock__c> stocks){
		upsert stocks;
	}

	public void deleteStock(List<Stock__c> stocks){
		delete stocks;
	}

}